Algoritmo "parouimpar"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo Henrique
// Data atual  : 21/06/2020
Var
// Seção de Declarações das variáveis
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("digite um valor: ")
leia (num)

se (num mod 2) =0 entao
escreval ("valor par")
senao
escreval ("valor impar")

fimse

Fimalgoritmo